/**
 * ~225 common grocery/household items mapped to default category names.
 * Used to seed the system item library (created_by = NULL).
 */
export const DEFAULT_ITEMS: { name: string; category: string }[] = [
  // ── Produce (~30) ──
  { name: 'Apples', category: 'Produce' },
  { name: 'Bananas', category: 'Produce' },
  { name: 'Oranges', category: 'Produce' },
  { name: 'Lemons', category: 'Produce' },
  { name: 'Limes', category: 'Produce' },
  { name: 'Grapes', category: 'Produce' },
  { name: 'Strawberries', category: 'Produce' },
  { name: 'Blueberries', category: 'Produce' },
  { name: 'Avocados', category: 'Produce' },
  { name: 'Tomatoes', category: 'Produce' },
  { name: 'Onions', category: 'Produce' },
  { name: 'Garlic', category: 'Produce' },
  { name: 'Potatoes', category: 'Produce' },
  { name: 'Sweet Potatoes', category: 'Produce' },
  { name: 'Carrots', category: 'Produce' },
  { name: 'Celery', category: 'Produce' },
  { name: 'Broccoli', category: 'Produce' },
  { name: 'Cauliflower', category: 'Produce' },
  { name: 'Spinach', category: 'Produce' },
  { name: 'Lettuce', category: 'Produce' },
  { name: 'Kale', category: 'Produce' },
  { name: 'Cucumbers', category: 'Produce' },
  { name: 'Bell Peppers', category: 'Produce' },
  { name: 'Jalapenos', category: 'Produce' },
  { name: 'Mushrooms', category: 'Produce' },
  { name: 'Zucchini', category: 'Produce' },
  { name: 'Corn', category: 'Produce' },
  { name: 'Green Beans', category: 'Produce' },
  { name: 'Cilantro', category: 'Produce' },
  { name: 'Ginger', category: 'Produce' },

  // ── Meat (~20) ──
  { name: 'Chicken Breast', category: 'Meat' },
  { name: 'Chicken Thighs', category: 'Meat' },
  { name: 'Ground Beef', category: 'Meat' },
  { name: 'Ground Turkey', category: 'Meat' },
  { name: 'Steak', category: 'Meat' },
  { name: 'Pork Chops', category: 'Meat' },
  { name: 'Bacon', category: 'Meat' },
  { name: 'Sausage', category: 'Meat' },
  { name: 'Hot Dogs', category: 'Meat' },
  { name: 'Salmon', category: 'Meat' },
  { name: 'Shrimp', category: 'Meat' },
  { name: 'Tilapia', category: 'Meat' },
  { name: 'Tuna Steaks', category: 'Meat' },
  { name: 'Ham', category: 'Meat' },
  { name: 'Turkey Breast', category: 'Meat' },
  { name: 'Lamb Chops', category: 'Meat' },
  { name: 'Pork Tenderloin', category: 'Meat' },
  { name: 'Deli Turkey', category: 'Meat' },
  { name: 'Deli Ham', category: 'Meat' },
  { name: 'Pepperoni', category: 'Meat' },

  // ── Dairy (~20) ──
  { name: 'Milk', category: 'Dairy' },
  { name: 'Eggs', category: 'Dairy' },
  { name: 'Butter', category: 'Dairy' },
  { name: 'Yogurt', category: 'Dairy' },
  { name: 'Greek Yogurt', category: 'Dairy' },
  { name: 'Cheddar Cheese', category: 'Dairy' },
  { name: 'Mozzarella', category: 'Dairy' },
  { name: 'Parmesan', category: 'Dairy' },
  { name: 'Cream Cheese', category: 'Dairy' },
  { name: 'Sour Cream', category: 'Dairy' },
  { name: 'Heavy Cream', category: 'Dairy' },
  { name: 'Half and Half', category: 'Dairy' },
  { name: 'Cottage Cheese', category: 'Dairy' },
  { name: 'Shredded Cheese', category: 'Dairy' },
  { name: 'Sliced Cheese', category: 'Dairy' },
  { name: 'Almond Milk', category: 'Dairy' },
  { name: 'Oat Milk', category: 'Dairy' },
  { name: 'Whipped Cream', category: 'Dairy' },
  { name: 'String Cheese', category: 'Dairy' },
  { name: 'Ricotta', category: 'Dairy' },

  // ── Bakery (~15) ──
  { name: 'Bread', category: 'Bakery' },
  { name: 'Tortillas', category: 'Bakery' },
  { name: 'Bagels', category: 'Bakery' },
  { name: 'English Muffins', category: 'Bakery' },
  { name: 'Hamburger Buns', category: 'Bakery' },
  { name: 'Hot Dog Buns', category: 'Bakery' },
  { name: 'Pita Bread', category: 'Bakery' },
  { name: 'Croissants', category: 'Bakery' },
  { name: 'Dinner Rolls', category: 'Bakery' },
  { name: 'Muffins', category: 'Bakery' },
  { name: 'Donuts', category: 'Bakery' },
  { name: 'Cake', category: 'Bakery' },
  { name: 'Pie', category: 'Bakery' },
  { name: 'Cornbread', category: 'Bakery' },
  { name: 'Naan', category: 'Bakery' },

  // ── Frozen (~20) ──
  { name: 'Ice Cream', category: 'Frozen' },
  { name: 'Frozen Pizza', category: 'Frozen' },
  { name: 'Frozen Vegetables', category: 'Frozen' },
  { name: 'Frozen Fruit', category: 'Frozen' },
  { name: 'Frozen Waffles', category: 'Frozen' },
  { name: 'Frozen Burritos', category: 'Frozen' },
  { name: 'Fish Sticks', category: 'Frozen' },
  { name: 'Chicken Nuggets', category: 'Frozen' },
  { name: 'Frozen Fries', category: 'Frozen' },
  { name: 'Popsicles', category: 'Frozen' },
  { name: 'Frozen Dinners', category: 'Frozen' },
  { name: 'Frozen Meatballs', category: 'Frozen' },
  { name: 'Frozen Shrimp', category: 'Frozen' },
  { name: 'Frozen Corn', category: 'Frozen' },
  { name: 'Frozen Peas', category: 'Frozen' },
  { name: 'Frozen Broccoli', category: 'Frozen' },
  { name: 'Frozen Berries', category: 'Frozen' },
  { name: 'Egg Rolls', category: 'Frozen' },
  { name: 'Frozen Pancakes', category: 'Frozen' },
  { name: 'Ice Cream Sandwiches', category: 'Frozen' },

  // ── Beverages (~20) ──
  { name: 'Water', category: 'Beverages' },
  { name: 'Sparkling Water', category: 'Beverages' },
  { name: 'Coffee', category: 'Beverages' },
  { name: 'Tea', category: 'Beverages' },
  { name: 'Orange Juice', category: 'Beverages' },
  { name: 'Apple Juice', category: 'Beverages' },
  { name: 'Soda', category: 'Beverages' },
  { name: 'Lemonade', category: 'Beverages' },
  { name: 'Cranberry Juice', category: 'Beverages' },
  { name: 'Grape Juice', category: 'Beverages' },
  { name: 'Sports Drinks', category: 'Beverages' },
  { name: 'Energy Drinks', category: 'Beverages' },
  { name: 'Coconut Water', category: 'Beverages' },
  { name: 'Hot Chocolate', category: 'Beverages' },
  { name: 'Iced Tea', category: 'Beverages' },
  { name: 'Kombucha', category: 'Beverages' },
{ name: 'Creamer', category: 'Beverages' },
  { name: 'Smoothie Mix', category: 'Beverages' },

  // ── Snacks (~20) ──
  { name: 'Chips', category: 'Snacks' },
  { name: 'Tortilla Chips', category: 'Snacks' },
  { name: 'Crackers', category: 'Snacks' },
  { name: 'Pretzels', category: 'Snacks' },
  { name: 'Popcorn', category: 'Snacks' },
  { name: 'Granola Bars', category: 'Snacks' },
  { name: 'Trail Mix', category: 'Snacks' },
  { name: 'Nuts', category: 'Snacks' },
  { name: 'Dried Fruit', category: 'Snacks' },
  { name: 'Fruit Snacks', category: 'Snacks' },
  { name: 'Cookies', category: 'Snacks' },
  { name: 'Chocolate', category: 'Snacks' },
  { name: 'Candy', category: 'Snacks' },
  { name: 'Beef Jerky', category: 'Snacks' },
  { name: 'Rice Cakes', category: 'Snacks' },
  { name: 'Hummus', category: 'Snacks' },
  { name: 'Salsa', category: 'Snacks' },
  { name: 'Guacamole', category: 'Snacks' },
  { name: 'Peanut Butter', category: 'Snacks' },
  { name: 'Applesauce', category: 'Snacks' },

  // ── Canned Goods (~20) ──
  { name: 'Canned Tomatoes', category: 'Canned Goods' },
  { name: 'Tomato Paste', category: 'Canned Goods' },
  { name: 'Tomato Sauce', category: 'Canned Goods' },
  { name: 'Pasta Sauce', category: 'Canned Goods' },
  { name: 'Chicken Broth', category: 'Canned Goods' },
  { name: 'Beef Broth', category: 'Canned Goods' },
  { name: 'Vegetable Broth', category: 'Canned Goods' },
  { name: 'Canned Beans', category: 'Canned Goods' },
  { name: 'Black Beans', category: 'Canned Goods' },
  { name: 'Kidney Beans', category: 'Canned Goods' },
  { name: 'Chickpeas', category: 'Canned Goods' },
  { name: 'Canned Corn', category: 'Canned Goods' },
  { name: 'Canned Tuna', category: 'Canned Goods' },
  { name: 'Canned Chicken', category: 'Canned Goods' },
  { name: 'Coconut Milk', category: 'Canned Goods' },
  { name: 'Canned Soup', category: 'Canned Goods' },
  { name: 'Canned Pumpkin', category: 'Canned Goods' },
  { name: 'Canned Pineapple', category: 'Canned Goods' },
  { name: 'Canned Green Chiles', category: 'Canned Goods' },
  { name: 'Enchilada Sauce', category: 'Canned Goods' },

  // ── Household (~25) ──
  { name: 'Paper Towels', category: 'Household' },
  { name: 'Toilet Paper', category: 'Household' },
  { name: 'Tissues', category: 'Household' },
  { name: 'Trash Bags', category: 'Household' },
  { name: 'Dish Soap', category: 'Household' },
  { name: 'Dishwasher Detergent', category: 'Household' },
  { name: 'Laundry Detergent', category: 'Household' },
  { name: 'Dryer Sheets', category: 'Household' },
  { name: 'All-Purpose Cleaner', category: 'Household' },
  { name: 'Glass Cleaner', category: 'Household' },
  { name: 'Disinfecting Wipes', category: 'Household' },
  { name: 'Sponges', category: 'Household' },
  { name: 'Aluminum Foil', category: 'Household' },
  { name: 'Plastic Wrap', category: 'Household' },
  { name: 'Parchment Paper', category: 'Household' },
  { name: 'Ziplock Bags', category: 'Household' },
  { name: 'Paper Plates', category: 'Household' },
  { name: 'Napkins', category: 'Household' },
  { name: 'Light Bulbs', category: 'Household' },
  { name: 'Batteries', category: 'Household' },
  { name: 'Air Freshener', category: 'Household' },
  { name: 'Candles', category: 'Household' },
  { name: 'Hand Soap', category: 'Household' },
  { name: 'Bleach', category: 'Household' },
  { name: 'Fabric Softener', category: 'Household' },

  // ── Personal Care (~20) ──
  { name: 'Shampoo', category: 'Personal Care' },
  { name: 'Conditioner', category: 'Personal Care' },
  { name: 'Body Wash', category: 'Personal Care' },
  { name: 'Bar Soap', category: 'Personal Care' },
  { name: 'Toothpaste', category: 'Personal Care' },
  { name: 'Toothbrush', category: 'Personal Care' },
  { name: 'Mouthwash', category: 'Personal Care' },
  { name: 'Floss', category: 'Personal Care' },
  { name: 'Deodorant', category: 'Personal Care' },
  { name: 'Lotion', category: 'Personal Care' },
  { name: 'Sunscreen', category: 'Personal Care' },
  { name: 'Razor Blades', category: 'Personal Care' },
  { name: 'Shaving Cream', category: 'Personal Care' },
  { name: 'Cotton Balls', category: 'Personal Care' },
  { name: 'Q-Tips', category: 'Personal Care' },
  { name: 'Band-Aids', category: 'Personal Care' },
  { name: 'Pain Reliever', category: 'Personal Care' },
  { name: 'Vitamins', category: 'Personal Care' },
  { name: 'Lip Balm', category: 'Personal Care' },
  { name: 'Face Wash', category: 'Personal Care' },

  // ── Other (~15) ──
  { name: 'Salt', category: 'Other' },
  { name: 'Pepper', category: 'Other' },
  { name: 'Olive Oil', category: 'Other' },
  { name: 'Vegetable Oil', category: 'Other' },
  { name: 'Flour', category: 'Other' },
  { name: 'Sugar', category: 'Other' },
  { name: 'Brown Sugar', category: 'Other' },
  { name: 'Rice', category: 'Other' },
  { name: 'Pasta', category: 'Other' },
  { name: 'Cereal', category: 'Other' },
  { name: 'Oatmeal', category: 'Other' },
  { name: 'Honey', category: 'Other' },
  { name: 'Maple Syrup', category: 'Other' },
  { name: 'Vinegar', category: 'Other' },
  { name: 'Soy Sauce', category: 'Other' },
  { name: 'Hot Sauce', category: 'Other' },
  { name: 'Ketchup', category: 'Other' },
  { name: 'Mustard', category: 'Other' },
  { name: 'Mayonnaise', category: 'Other' },
  { name: 'Ranch Dressing', category: 'Other' },
];
